/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalpages;

import book_tracker_system.DASHBOARD;
import config.DBConnector;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author lbixt
 */
public class studentFormForm extends javax.swing.JFrame {

    /**
     * Creates new form newbornForm
     */
    public studentFormForm() {
        initComponents();
    }
   
public String action;
public void close(){
    this.dispose();
      DASHBOARD dash =new DASHBOARD();
      dash.setVisible(true);
       studentPage np = new studentPage();
       dash.maindesktop.add(np).setVisible(true);
}
  Color navcolor =new Color(204,255,255);
    Color headcolor = new Color(102,255,255);
    Color bodycolor = new Color(255,255,255);
 public void reset(){
        b_id.setText("");
         b_fname.setText("");
          b_lname.setText("");
          b_date.setText("");
         
          b_address.setText("");
        
                  
    
  
   
    }
  int validateRegister(){
        int result;
        if(b_fname.getText().isEmpty()||b_lname.getText().isEmpty()||b_date.getText().isEmpty()||b_gender.getText().isEmpty()||b_date.getText().isEmpty()||b_address.getText().isEmpty()){
            result = 0;
        }else{
            result = 1;
        }
        return result;   
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        b_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        b_date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        b_fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        b_gender = new javax.swing.JTextField();
        b_lname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        b_address = new javax.swing.JTextArea();
        clear = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        save = new javax.swing.JPanel();
        SAVE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT FORM");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        close.setBackground(new java.awt.Color(102, 255, 255));
        close.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("X");
        close.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 10, -1));

        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("STUDENT ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 120, 20));

        b_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        b_id.setEnabled(false);
        jPanel1.add(b_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("(mm-dd-yyyy)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Ex.(2-1-2001)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        b_date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        b_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_dateActionPerformed(evt);
            }
        });
        b_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b_dateKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_dateKeyTyped(evt);
            }
        });
        jPanel1.add(b_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 190, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("DATE OF BIRTH:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 140, -1));

        b_fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        b_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_fnameKeyTyped(evt);
            }
        });
        jPanel1.add(b_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("FIRST NAME:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 110, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("LAST NAME:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("GENDER:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        b_gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        b_gender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b_genderKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_genderKeyTyped(evt);
            }
        });
        jPanel1.add(b_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 140, 40));

        b_lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        b_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_lnameKeyTyped(evt);
            }
        });
        jPanel1.add(b_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ADDRESS:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 130, 20));

        b_address.setColumns(20);
        b_address.setRows(5);
        b_address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        b_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_addressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(b_address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 190, 130));

        clear.setBackground(new java.awt.Color(102, 255, 255));
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CLEAR");
        clear.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 30));

        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 80, 50));

        save.setBackground(new java.awt.Color(102, 255, 255));
        save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        save.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SAVE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SAVE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SAVE.setText("SAVE");
        save.add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 30));

        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 80, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_closeMouseClicked

    private void b_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_dateActionPerformed

    private void b_dateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_dateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_dateKeyPressed

    private void b_dateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_dateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_b_dateKeyTyped

    private void b_fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_fnameKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_b_fnameKeyTyped

    private void b_genderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_genderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_genderKeyPressed

    private void b_genderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_genderKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_b_genderKeyTyped

    private void b_lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_lnameKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_b_lnameKeyTyped

    private void b_addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_addressKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_b_addressKeyTyped

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
reset();
    }//GEN-LAST:event_clearMouseClicked

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        clear.setBackground(bodycolor);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
        clear.setBackground(navcolor);
    }//GEN-LAST:event_clearMouseExited

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        // TODO add your handling code here:
        if(action.equals("Add")){
           
            DBConnector dbc = new DBConnector();
            int check = validateRegister();
            if(check == 1){
            int result =  dbc.insertData("INSERT INTO tbl_students (firstname, lastname, birthdate, gender, address) "
                +"VALUES ('"+b_fname.getText()+"','"+b_lname.getText()+"','"+b_date.getText()+"','"+b_gender.getText()+"','"+b_address.getText()+"')");
            if(result==1){
                JOptionPane.showMessageDialog(null,"Successfully Save!!!");
                close();
            }else{
                System.out.println("Saving Data Failed!");
            }
            }else{
            JOptionPane.showMessageDialog(null, "All fields are required!");
        }  
            
        }else if(action.equals("Update")){
            DBConnector dbc = new DBConnector();
            int check = validateRegister();
            if(check == 1){
            dbc.updateData("UPDATE tbl_students SET firstname= '"+b_fname.getText()+"',lastname='"+b_lname.getText()+"', birthdate='"+b_date.getText()+
                "',gender='"+b_gender.getText()+"',address='"+b_address.getText()+"'"
                +"WHERE student_id ='"+b_id.getText()+"'");

            close();
        }else{
            JOptionPane.showMessageDialog(null,"No Action Selected!");
            close();
        }
            }else{
            JOptionPane.showMessageDialog(null, "All fields are required!");
        }  
    }//GEN-LAST:event_saveMouseClicked

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        // TODO add your handling code here:
        save.setBackground(bodycolor);
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        // TODO add your handling code here:
        save.setBackground(navcolor);
    }//GEN-LAST:event_saveMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentFormForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentFormForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentFormForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentFormForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentFormForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel SAVE;
    public javax.swing.JTextArea b_address;
    public javax.swing.JTextField b_date;
    public javax.swing.JTextField b_fname;
    public javax.swing.JTextField b_gender;
    public javax.swing.JTextField b_id;
    public javax.swing.JTextField b_lname;
    public javax.swing.JPanel clear;
    private javax.swing.JPanel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel save;
    // End of variables declaration//GEN-END:variables
}
