/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package book_tracker_system;

import config.Aconnector;
import forms.loginForm;
import internalpages.adminPage;
import internalpages.bookPage;
import internalpages.dashboardPage;
import internalpages.studentPage;

import internalpages.libraryPage;
import internalpages.settingPage;
import java.awt.Color;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author lbixt
 */
public class DASHBOARD extends javax.swing.JFrame {

    /**
     * Creates new form DASHBOARD
     */
    public DASHBOARD() {
        initComponents();
         dashboardPage dbc =new dashboardPage();
    }
 Color navcolor =new Color(204,255,255);
    Color headcolor = new Color(102,255,255);
    Color bodycolor = new Color(255,255,255);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        baby = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        schedule = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        admin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dashpane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        appointment = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        maindesktop = new javax.swing.JDesktopPane();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setBackground(new java.awt.Color(204, 255, 255));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baby.setBackground(new java.awt.Color(204, 255, 255));
        baby.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                babyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                babyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                babyMouseExited(evt);
            }
        });
        baby.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STUDENT INFO");
        baby.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 130, -1));

        navbar.add(baby, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 130, 60));

        schedule.setBackground(new java.awt.Color(204, 255, 255));
        schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scheduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scheduleMouseExited(evt);
            }
        });
        schedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schedule.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("LIBRARY ");
        schedule.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 130, -1));

        navbar.add(schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 130, 60));

        settings.setBackground(new java.awt.Color(204, 255, 255));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsMouseExited(evt);
            }
        });
        settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SETTINGS");
        settings.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 130, -1));

        navbar.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 130, 60));

        admin.setBackground(new java.awt.Color(204, 255, 255));
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminMouseExited(evt);
            }
        });
        admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LIBRARIAN");
        admin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 130, -1));

        navbar.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 130, 60));

        dashpane.setBackground(new java.awt.Color(204, 255, 255));
        dashpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashpaneMouseExited(evt);
            }
        });
        dashpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        dashpane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 130, -1));

        navbar.add(dashpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 130, 60));

        appointment.setBackground(new java.awt.Color(204, 255, 255));
        appointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appointmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appointmentMouseExited(evt);
            }
        });
        appointment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("BORROW BOOK");
        appointment.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 130, -1));

        navbar.add(appointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 130, 60));

        jPanel1.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 530));

        header.setBackground(new java.awt.Color(102, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LIBRARY BOOK TRACKER SYSTEM");
        header.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 540, -1));

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setText("x");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        header.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 40, -1));

        minimize.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        minimize.setText("_");
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        header.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 40, -1));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 570, 60));

        maindesktop.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book-clipart-md.png"))); // NOI18N
        maindesktop.add(jLabel9);
        jLabel9.setBounds(60, 0, 470, 470);

        jPanel1.add(maindesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 570, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void babyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_babyMouseClicked
        // TODO add your handling code here:
       studentPage ad =new studentPage();
        maindesktop.add(ad).setVisible(true);
    }//GEN-LAST:event_babyMouseClicked

    private void babyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_babyMouseEntered
        // TODO add your handling code here:
        baby.setBackground(bodycolor);
    }//GEN-LAST:event_babyMouseEntered

    private void babyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_babyMouseExited
        // TODO add your handling code here:
        baby.setBackground(navcolor);
    }//GEN-LAST:event_babyMouseExited

    private void scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleMouseClicked
        // TODO add your handling code here:
         libraryPage ad =new libraryPage();
        maindesktop.add(ad).setVisible(true);
        
    }//GEN-LAST:event_scheduleMouseClicked

    private void scheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleMouseEntered
        // TODO add your handling code here:
        schedule.setBackground(bodycolor);
    }//GEN-LAST:event_scheduleMouseEntered

    private void scheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleMouseExited
        // TODO add your handling code here:
        schedule.setBackground(navcolor);
    }//GEN-LAST:event_scheduleMouseExited

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        // TODO add your handling code here:
        /*settingPage ad =new settingPage();
        maindesktop.add(ad).setVisible(true);
        */
        
        settingPage profile = new settingPage();
try {
    loginForm login = new loginForm();
    String fname = login.a_username;
    String birthdate = login.a_birthdate;
    String contact = login.a_contact;

    profile.b_fname.setText(fname);
    profile.b_date.setText(birthdate);
    profile.b_num.setText(contact);

    byte[] profileImage = login.my_Image;
    ImageIcon imageIcon = new ImageIcon(new ImageIcon(profileImage).getImage().getScaledInstance(184, 200, Image.SCALE_SMOOTH));
   
} catch (Exception e) {
    // Handle the exception appropriately
}
maindesktop.add(profile).setVisible(true);
    }//GEN-LAST:event_settingsMouseClicked

    private void settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseEntered
        // TODO add your handling code here:
        settings.setBackground(bodycolor);
    }//GEN-LAST:event_settingsMouseEntered

    private void settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseExited
        // TODO add your handling code here:
        settings.setBackground(navcolor);
    }//GEN-LAST:event_settingsMouseExited
public void table2() throws SQLException{
      Aconnector dbc = new Aconnector();
        ResultSet rs =dbc.getData("SELECT tbl_admin.firstname, "
        +"tbl_admin.lastname, tbl_admin.birthdate, "
        +"tbl_admin.contact "
        +"FROM tbl_admin");
        adminPage.admin_table.setModel(DbUtils.resultSetToTableModel(rs));
}
        
    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        // TODO add your handling code here:
        
       
        
        
        
        adminPage ad =new adminPage();
        maindesktop.add(ad).setVisible(true);
       
    }//GEN-LAST:event_adminMouseClicked

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        // TODO add your handling code here:
        admin.setBackground(bodycolor);
    }//GEN-LAST:event_adminMouseEntered

    private void adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseExited
        // TODO add your handling code here: settings.setBackground(bodycolor);
        admin.setBackground(navcolor);
    }//GEN-LAST:event_adminMouseExited

    private void dashpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpaneMouseClicked
        // TODO add your handling code here:
          dashboardPage ad =new dashboardPage();
        maindesktop.add(ad).setVisible(true);
    }//GEN-LAST:event_dashpaneMouseClicked

    private void dashpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpaneMouseEntered
        // TODO add your handling code here:
        dashpane.setBackground(bodycolor);
    }//GEN-LAST:event_dashpaneMouseEntered

    private void dashpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpaneMouseExited
        // TODO add your handling code here:
        dashpane.setBackground(navcolor);
    }//GEN-LAST:event_dashpaneMouseExited

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JFrame db =new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog ( db, "Confirm if you want to Exit", "EXIT",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION ){
        System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_minimizeActionPerformed

    private void appointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentMouseClicked
        // TODO add your handling code here:
         bookPage ad =new bookPage();
        maindesktop.add(ad).setVisible(true);
    }//GEN-LAST:event_appointmentMouseClicked

    private void appointmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentMouseEntered
        // TODO add your handling code here:
         appointment.setBackground(bodycolor);
    }//GEN-LAST:event_appointmentMouseEntered

    private void appointmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentMouseExited
        // TODO add your handling code here:.
         appointment.setBackground(navcolor);
    }//GEN-LAST:event_appointmentMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DASHBOARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin;
    private javax.swing.JPanel appointment;
    private javax.swing.JPanel baby;
    private javax.swing.JPanel dashpane;
    private javax.swing.JButton exit;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JDesktopPane maindesktop;
    private javax.swing.JButton minimize;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel schedule;
    private javax.swing.JPanel settings;
    // End of variables declaration//GEN-END:variables
}
